version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
      - './server.pem:/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      - './server.key:/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      - './client.pem:/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,SSL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,SSL://:9093
      - KAFKA_TLS_TYPE=PEM
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_SSL_KEYSTORE_TYPE=PEM
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.pem
      - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PEM
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.pem
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
